name: telegram

on:
  push:
    branches: [ master ]  
  release:
    types:
      - published    
jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:        
    - uses: avkviring/telegram-github-action@v0.0.13
      env:
        telegram_to: ${{ secrets.TELEGRAM_USER_ID }}  
        telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        event: ${{ toJson(github.event) }}
